/* 
**  mod_reverse_toupper.c -- Apache sample reverse_toupper module
**  [Autogenerated via ``apxs -n reverse_toupper -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_reverse_toupper.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /reverse_toupper in as follows:
**
**    #   apache2.conf
**    LoadModule reverse_toupper_module modules/mod_reverse_toupper.so
**    <Location /reverse_toupper>
**    SetHandler reverse_toupper
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /reverse_toupper and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/reverse_toupper 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_reverse_toupper.c
*/ 
#include <ctype.h>
#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "util_filter.h"
#include "http_log.h"

static apr_status_t my_output_filter(ap_filter_t *f,
                                     apr_bucket_brigade *pbbIn) {
    ap_log_rerror(APLOG_MARK,
                 APLOG_ERR, 0, f->r, 
                 "Enter my_output_filter");
    apr_bucket *pbktIn;
    apr_bucket_brigade *pbbOut;
    pbbOut = apr_brigade_create(f->r->pool, f->r->connection->bucket_alloc);

    pbktIn = APR_BRIGADE_FIRST(pbbIn);
    while (pbktIn != APR_BRIGADE_SENTINEL(pbbIn))
    {
        const char *data;
        apr_size_t len;
        char *buf;
        apr_size_t n;
        apr_bucket *pbktOut;

        if(APR_BUCKET_IS_EOS(pbktIn)) {
            apr_bucket *pbktEOS=apr_bucket_eos_create(f->r->connection->bucket_alloc);
            APR_BRIGADE_INSERT_TAIL(pbbOut,pbktEOS);
            continue;
        } else if (APR_BUCKET_IS_METADATA(pbktIn)) {
            APR_BUCKET_REMOVE(pbktIn);
            APR_BRIGADE_INSERT_TAIL(pbbOut, pbktIn);
            pbktIn = APR_BUCKET_NEXT(pbktIn);
            continue;
        }
        apr_bucket_read(pbktIn,&data,&len,APR_BLOCK_READ);
        buf=malloc(len+1);

        // Let's reverse the buffer
        for(n=0 ; n < len ; ++n)
            buf[n]= toupper(data[n]);
        buf[len] = '\0';
        ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, f->r, "Content of buffer %s", buf);
        // TODO: Something goes wrong after this point
        pbktOut = apr_bucket_heap_create(buf,len,free, 0);
        APR_BRIGADE_INSERT_TAIL(pbbOut, pbktOut);
        pbktIn = APR_BUCKET_NEXT(pbktIn);
    }
    apr_status_t rv = ap_pass_brigade(f->next,pbbOut);
    apr_brigade_cleanup(pbbOut);
    return APR_SUCCESS;
}


/* The sample content handler */
static int reverse_toupper_handler(request_rec *r)
{
    ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r, "Enter my module for %s", r->the_request);
    ap_add_output_filter("my_output_filter", NULL, r, r->connection);
    return OK;
}

static void reverse_toupper_register_hooks(apr_pool_t *p)
{
    ap_hook_insert_filter(reverse_toupper_handler, NULL, NULL, APR_HOOK_MIDDLE);
    ap_register_output_filter("my_output_filter", my_output_filter, NULL, AP_FTYPE_CONTENT_SET);

}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA reverse_toupper_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    reverse_toupper_register_hooks  /* register hooks                      */
};

